In [97]:
import numpy as np
import pygame
import importlib
import src.simulation as sim
import src.transformations as t
import src.change_of_coordinates as coc

In [81]:
importlib.reload(sim)

<module 'src.simulation' from '/Users/alfred/Documents/affine_transformations/src/simulation.py'>

In [82]:
importlib.reload(t)

<module 'src.transformations' from '/Users/alfred/Documents/affine_transformations/src/transformations.py'>

In [98]:
importlib.reload(coc)

<module 'src.change_of_coordinates' from '/Users/alfred/Documents/affine_transformations/src/change_of_coordinates.py'>

In [83]:
def render(screen, vertices, faces, screen_height, camera_location):
    screen.fill((255, 255, 255))

    sim.draw_wireframe(screen, sim.perspective_projection(camera_location, vertices), faces, screen_height)
    
    pygame.display.update()

In [105]:
screen_width = 800
screen_height = 800
center = np.array([400., 400., 400.])
camera_location = np.array([400., 400., -100.])

In [106]:
vertices, faces = sim.init_cuboid(center, 50, 50, 50)
vertices, faces

(array([[450., 450., 450.],
        [450., 450., 350.],
        [350., 450., 450.],
        [350., 450., 350.],
        [450., 350., 450.],
        [450., 350., 350.],
        [350., 350., 450.],
        [350., 350., 350.]]),
 array([[0, 4, 6, 2],
        [1, 3, 7, 5],
        [0, 2, 3, 1],
        [0, 1, 5, 4],
        [1, 3, 7, 5],
        [2, 6, 7, 3]]))

In [107]:
pygame.init()

screen = pygame.display.set_mode((screen_width, screen_height))
render(screen, vertices, faces, screen_height, camera_location)

**Translation**

In [108]:
t.translation(center, vertices, 100, 0)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 450., 450.],
        [550., 450., 350.],
        [450., 450., 450.],
        [450., 450., 350.],
        [550., 350., 450.],
        [550., 350., 350.],
        [450., 350., 450.],
        [450., 350., 350.]]),
 array([500., 400., 400.]))

In [114]:
t.translation(center, vertices, 100, 1)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 450.],
        [550., 550., 350.],
        [450., 550., 450.],
        [450., 550., 350.],
        [550., 450., 450.],
        [550., 450., 350.],
        [450., 450., 450.],
        [450., 450., 350.]]),
 array([500., 500., 400.]))

In [116]:
t.translation(center, vertices, -100, 2)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 250.],
        [550., 550., 150.],
        [450., 550., 250.],
        [450., 550., 150.],
        [550., 450., 250.],
        [550., 450., 150.],
        [450., 450., 250.],
        [450., 450., 150.]]),
 array([500., 500., 200.]))

**Uniform Scale**

In [117]:
t.uniform_scale(center, vertices, 2)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[600., 600., 300.],
        [600., 600., 100.],
        [400., 600., 300.],
        [400., 600., 100.],
        [600., 400., 300.],
        [600., 400., 100.],
        [400., 400., 300.],
        [400., 400., 100.]]),
 array([500., 500., 200.]))

In [118]:
t.uniform_scale(center, vertices, 0.5)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 250.],
        [550., 550., 150.],
        [450., 550., 250.],
        [450., 550., 150.],
        [550., 450., 250.],
        [550., 450., 150.],
        [450., 450., 250.],
        [450., 450., 150.]]),
 array([500., 500., 200.]))

**Rotation**

In [119]:
t.rotation_about_y(center, vertices, np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[532.1019761 , 550.        , 263.00367553],
        [563.00367553, 550.        , 167.8980239 ],
        [436.99632447, 550.        , 232.1019761 ],
        [467.8980239 , 550.        , 136.99632447],
        [532.1019761 , 450.        , 263.00367553],
        [563.00367553, 450.        , 167.8980239 ],
        [436.99632447, 450.        , 232.1019761 ],
        [467.8980239 , 450.        , 136.99632447]]),
 array([500., 500., 200.]))

In [120]:
t.rotation_about_y(center, vertices, np.pi / 20)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[521.85080122, 550.        , 267.2498512 ],
        [567.2498512 , 550.        , 178.14919878],
        [432.7501488 , 550.        , 221.85080122],
        [478.14919878, 550.        , 132.7501488 ],
        [521.85080122, 450.        , 267.2498512 ],
        [567.2498512 , 450.        , 178.14919878],
        [432.7501488 , 450.        , 221.85080122],
        [478.14919878, 450.        , 132.7501488 ]]),
 array([500., 500., 200.]))

In [121]:
t.rotation_about_y(center, vertices, np.pi / 15)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[507.39127852, 550.        , 270.32331763],
        [570.32331763, 550.        , 192.60872148],
        [429.67668237, 550.        , 207.39127852],
        [492.60872148, 550.        , 129.67668237],
        [507.39127852, 450.        , 270.32331763],
        [570.32331763, 450.        , 192.60872148],
        [429.67668237, 450.        , 207.39127852],
        [492.60872148, 450.        , 129.67668237]]),
 array([500., 500., 200.]))

In [122]:
t.rotation_about_y(center, vertices, - np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[528.76062385, 550.        , 264.5974188 ],
        [564.5974188 , 550.        , 171.23937615],
        [435.4025812 , 550.        , 228.76062385],
        [471.23937615, 550.        , 135.4025812 ],
        [528.76062385, 450.        , 264.5974188 ],
        [564.5974188 , 450.        , 171.23937615],
        [435.4025812 , 450.        , 228.76062385],
        [471.23937615, 450.        , 135.4025812 ]]),
 array([500., 500., 200.]))

In [123]:
t.rotation_about_y(center, vertices, - np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[547.31467893, 550.        , 252.54827455],
        [552.54827455, 550.        , 152.68532107],
        [447.45172545, 550.        , 247.31467893],
        [452.68532107, 550.        , 147.45172545],
        [547.31467893, 450.        , 252.54827455],
        [552.54827455, 450.        , 152.68532107],
        [447.45172545, 450.        , 247.31467893],
        [452.68532107, 450.        , 147.45172545]]),
 array([500., 500., 200.]))