In [1]:
import numpy as np
import pygame
import importlib
import src.simulation as sim
import src.transformations as t
import src.change_of_coordinates as coc

pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
importlib.reload(sim)

<module 'src.simulation' from '/Users/alfred/Documents/affine_transformations/src/simulation.py'>

In [3]:
importlib.reload(t)

<module 'src.transformations' from '/Users/alfred/Documents/affine_transformations/src/transformations.py'>

In [4]:
importlib.reload(coc)

<module 'src.change_of_coordinates' from '/Users/alfred/Documents/affine_transformations/src/change_of_coordinates.py'>

In [5]:
def render(screen, vertices, faces, screen_height, camera_location):
    screen.fill((255, 255, 255))

    sim.draw_wireframe(screen, sim.perspective_projection(camera_location, vertices), faces, screen_height)
    
    pygame.display.update()

In [6]:
screen_width = 800
screen_height = 800
center = np.array([400., 400., 400.])
camera_location = np.array([400., 400., -100.])

In [7]:
vertices, faces = sim.init_cuboid(center, 50, 50, 50)
vertices, faces

(array([[450., 450., 450.],
        [450., 450., 350.],
        [350., 450., 450.],
        [350., 450., 350.],
        [450., 350., 450.],
        [450., 350., 350.],
        [350., 350., 450.],
        [350., 350., 350.]]),
 array([[0, 4, 6, 2],
        [1, 3, 7, 5],
        [0, 2, 3, 1],
        [0, 1, 5, 4],
        [1, 3, 7, 5],
        [2, 6, 7, 3]]))

In [8]:
pygame.init()

screen = pygame.display.set_mode((screen_width, screen_height))
render(screen, vertices, faces, screen_height, camera_location)

**Translation**

In [9]:
t.translation(center, vertices, 100, 0)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 450., 450.],
        [550., 450., 350.],
        [450., 450., 450.],
        [450., 450., 350.],
        [550., 350., 450.],
        [550., 350., 350.],
        [450., 350., 450.],
        [450., 350., 350.]]),
 array([500., 400., 400.]))

In [10]:
t.translation(center, vertices, 100, 1)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 450.],
        [550., 550., 350.],
        [450., 550., 450.],
        [450., 550., 350.],
        [550., 450., 450.],
        [550., 450., 350.],
        [450., 450., 450.],
        [450., 450., 350.]]),
 array([500., 500., 400.]))

In [11]:
t.translation(center, vertices, -100, 2)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 350.],
        [550., 550., 250.],
        [450., 550., 350.],
        [450., 550., 250.],
        [550., 450., 350.],
        [550., 450., 250.],
        [450., 450., 350.],
        [450., 450., 250.]]),
 array([500., 500., 300.]))

**Uniform Scale**

In [12]:
t.uniform_scale(center, vertices, 2)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[600., 600., 400.],
        [600., 600., 200.],
        [400., 600., 400.],
        [400., 600., 200.],
        [600., 400., 400.],
        [600., 400., 200.],
        [400., 400., 400.],
        [400., 400., 200.]]),
 array([500., 500., 300.]))

In [13]:
t.uniform_scale(center, vertices, 0.5)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[550., 550., 350.],
        [550., 550., 250.],
        [450., 550., 350.],
        [450., 550., 250.],
        [550., 450., 350.],
        [550., 450., 250.],
        [450., 450., 350.],
        [450., 450., 250.]]),
 array([500., 500., 300.]))

**Rotation**

In [14]:
t.rotation_about_y(center, vertices, np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[532.1019761 , 550.        , 363.00367553],
        [563.00367553, 550.        , 267.8980239 ],
        [436.99632447, 550.        , 332.1019761 ],
        [467.8980239 , 550.        , 236.99632447],
        [532.1019761 , 450.        , 363.00367553],
        [563.00367553, 450.        , 267.8980239 ],
        [436.99632447, 450.        , 332.1019761 ],
        [467.8980239 , 450.        , 236.99632447]]),
 array([500., 500., 300.]))

In [15]:
t.rotation_about_y(center, vertices, np.pi / 20)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[521.85080122, 550.        , 367.2498512 ],
        [567.2498512 , 550.        , 278.14919878],
        [432.7501488 , 550.        , 321.85080122],
        [478.14919878, 550.        , 232.7501488 ],
        [521.85080122, 450.        , 367.2498512 ],
        [567.2498512 , 450.        , 278.14919878],
        [432.7501488 , 450.        , 321.85080122],
        [478.14919878, 450.        , 232.7501488 ]]),
 array([500., 500., 300.]))

In [16]:
t.rotation_about_y(center, vertices, np.pi / 15)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[507.39127852, 550.        , 370.32331763],
        [570.32331763, 550.        , 292.60872148],
        [429.67668237, 550.        , 307.39127852],
        [492.60872148, 550.        , 229.67668237],
        [507.39127852, 450.        , 370.32331763],
        [570.32331763, 450.        , 292.60872148],
        [429.67668237, 450.        , 307.39127852],
        [492.60872148, 450.        , 229.67668237]]),
 array([500., 500., 300.]))

In [17]:
t.rotation_about_y(center, vertices, - np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[528.76062385, 550.        , 364.5974188 ],
        [564.5974188 , 550.        , 271.23937615],
        [435.4025812 , 550.        , 328.76062385],
        [471.23937615, 550.        , 235.4025812 ],
        [528.76062385, 450.        , 364.5974188 ],
        [564.5974188 , 450.        , 271.23937615],
        [435.4025812 , 450.        , 328.76062385],
        [471.23937615, 450.        , 235.4025812 ]]),
 array([500., 500., 300.]))

In [18]:
t.rotation_about_y(center, vertices, - np.pi / 10)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[547.31467893, 550.        , 352.54827455],
        [552.54827455, 550.        , 252.68532107],
        [447.45172545, 550.        , 347.31467893],
        [452.68532107, 550.        , 247.45172545],
        [547.31467893, 450.        , 352.54827455],
        [552.54827455, 450.        , 252.68532107],
        [447.45172545, 450.        , 347.31467893],
        [452.68532107, 450.        , 247.45172545]]),
 array([500., 500., 300.]))

In [22]:
t.rotation_about_z(center, vertices, np.pi / 15)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[568.81694107, 498.29487151, 352.54827455],
        [572.31890009, 494.405552  , 252.68532107],
        [501.99558246, 572.50750864, 347.31467893],
        [505.49754147, 568.61818913, 247.45172545],
        [494.50245853, 431.38181087, 352.54827455],
        [498.00441754, 427.49249136, 252.68532107],
        [427.68109991, 505.594448  , 347.31467893],
        [431.18305893, 501.70512849, 247.45172545]]),
 array([500., 500., 300.]))

In [27]:
t.rotation_about_x(center, vertices, np.pi / 15)
render(screen, vertices, faces, screen_height, camera_location)
vertices, center

(array([[568.81694107, 544.65557644, 327.75082187],
        [572.31890009, 456.22706208, 281.18759463],
        [501.99558246, 577.22946824, 260.86399502],
        [505.49754147, 488.80095388, 214.30076778],
        [494.50245853, 511.19904612, 385.69923222],
        [498.00441754, 422.77053176, 339.13600498],
        [427.68109991, 543.77293792, 318.81240537],
        [431.18305893, 455.34442356, 272.24917813]]),
 array([500., 500., 300.]))